# pktemple; Temple, Parker

spantree: mafghanistan.o
	g++ -Wall -g -o spantree mafghanistan.o
mafghanistan.o: mafghanistan.cpp mafghanistan.h handy.h
	g++ -Wall -g -c mafghanistan.cpp
clean:
	rm -f spantree mafghanistan.o
